### ISSUE TITLE
LogFilter cannot run on MacOS

### ISSUE THREAD

**Issue by rouxianmantou** [iookill/LogFilter#2]
Hello, I think LogFilter is a pretty good log tool for Android developers.

But recently, I met a problem, I changed my work OS to MacOS. Then it shows error :  "java.io.IOException: Cannot run program "adb": error=2, No such file or directory".

The java & adb runs well in the bash, how can I solve it, or how can I use LogFilter on MacOS?
Thanks a lot :)

**Comment by zhaozhe-ysy** [comment]
java虚拟机加载的时候没有adb相关的环境变量,如果执行adb的命令，建议在设定命令的参数里面使用全路径。
https://www.jianshu.com/p/f608f0f61e48
我参考这个改好了，在MacOS可以用了

**Comment by rouxianmantou** [comment]
> java虚拟机加载的时候没有adb相关的环境变量,如果执行adb的命令，建议在设定命令的参数里面使用全路径。
> https://www.jianshu.com/p/f608f0f61e48
> 我参考这个改好了，在MacOS可以用了

谢谢！我当时也是这么搞的，把adb改成绝对路径然后重新打了包就行了，忘更新问题状态了，再次感谢！
